# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
#checkout code
- checkout: self

#copy files to the build staging directory
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SSHFileCopyTargetMachine1'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**'
    targetFolder: 'c:\repo'
    isWindowsOnTarget: true
    cleanTargetFolder: true
    readyTimeout: '20000'

#publish build artifact
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: $(Build.ArtifactStagingDirectory)
#    ArtifactName: 'drop'
#    publishLocation: Container

#copy code to remote server
- script: echo Hello, world!
  displayName: 'Run a one-line script'
